### ISSUE TITLE
Actually only requires php version 5.3

### ISSUE THREAD

**Issue by jonathan-s** [nubs/random-name-generator#15]
... as far as I can see at least.

**Comment by nubs** [comment]
That is definitely true and feel free to use v0.1.0.  I am removing support for older versions of PHP in newer versions of the library, however.  It can be painful to maintain a library to run on the newest version of PHP while still supporting versions of the language released 6 years ago.  This is especially true when dependencies (including dev dependencies) are upgrading to new features from newer versions of the language.  For example, the newest version of phpunit only runs on PHP 5.6 and 7.0 and the previous version is stated to not be supported on PHP 7.

You may continue using v0.1.0 (at your own risk), but I don't plan on supporting that release or any release of this library on PHP 5.3 or PHP 5.4.  PHP 5.5 support may also be dropped soon.
