### ISSUE TITLE
Query:  cinam/randomizer as a dev dependency

### ISSUE THREAD

**Issue by jessedc** [nubs/random-name-generator#21]
I was just wondering if it would be more appropriate for the dev dependency on `cinam/randomizer` be marked as a main dependency since the main classes type hint `Cinam\Randomizer\Randomizer`. 

Cheers

**Comment by nubs** [comment]
You can see more information in #9, but cinam/randomizer is only offered as an optional randomizer.  You can leave that parameter out and it will just use built-in random functions instead.
