### ISSUE TITLE
Support PHP 8.0

### ISSUE THREAD

**Issue by jonathan-shahen** [nubs/random-name-generator#38]
**Describe the solution you'd like**
Update `composer.json` to allow `|| ^8.0`

```
$ composer update
Loading composer repositories with package information
Updating dependencies                                 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires nubs/random-name-generator ^2.1 -> satisfiable by nubs/random-name-generator[v2.1.0].
    - nubs/random-name-generator v2.1.0 requires php ~5.6 || ~7.0 -> your php version (8.0.0) does not satisfy that requirement.
```

**Comment by nubs** [comment]
Resolved by #40

**Comment by nubs** [comment]
Released in v2.2.0

**Comment by Estrella2019** [comment]
I was wondering if there is a way to add names to the generator as under game names I added over 100 names and none of them are actually coming out unless I have horrible rng

**Comment by nubs** [comment]
@Estrella2019, it should be possible to add new names. However, you may need to familiarize yourself with the format of the file assuming you are using the video game name generator. It is split into 3 sections separated by `----` to represent the first, middle, and last phrase of the generated name. Each line is then of the format `word[^similarWord|...]` where it will make sure that it won't add the word if any of the similar words have already been chosen in a previous section.

Also, make sure you are using the correct generator. There are 2 included: a video game name generator and an alliteration generator (Adjective Noun like: Bouncy Buffalo).

If you still need help, I'd recommend opening up an issue and including your changes.
